dataset:
  eval:
    datasets:
      cute80: /data/ocr/reg/evaluation/CUTE80
      icdar03: /data/ocr/reg/evaluation/IC03_867
      icdar13: /data/ocr/reg/evaluation/IC13_1015
      icdar15: /data/ocr/reg/evaluation/IC15_2077
      iiit5k: /data/ocr/reg/evaluation/IIIT5k_3000
      svt: /data/ocr/reg/evaluation/SVT
      svtp: /data/ocr/reg/evaluation/SVTP
    height: 48
    width: 160
  train:
    datasets:
      synth800k: /home/luning/dev/data/SynthText800k/synth_lmdb
    height: 48
    width: 160
eval:
  batch_size: 50
  case_sensitive: false
  interval: 1
  interval_iter: 1000
  loader_workers: 8
model:
  backbone:
    gcb:
      att_scale: true
      fusion_type: channel_add
      headers: 1
      layers:
      - false
      - true
      - true
      - true
      pooling_type: att
      ratio: 0.0625
  decoder:
    dropout: 0
    feed_forward_size: 2048
    stacks: 3
  encoder:
    dropout: 0.2
    feed_forward_size: 2048
    stacks: 3
  model_size: 512
  multiheads: 8
system:
  debug: false
  desc: base
  model_name: OCRTransformer
  outputs:
    checkpoints: /home/luning/dev/projects/master-tf/outputs/512_8_3_3_2048_2048_0.2_0_Adam_base/checkpoints
    root: /home/luning/dev/projects/master-tf/outputs/512_8_3_3_2048_2048_0.2_0_Adam_base
    tb_log_dir: /home/luning/dev/projects/master-tf/outputs/512_8_3_3_2048_2048_0.2_0_Adam_base/training_logs
    training_log: /home/luning/dev/projects/master-tf/outputs/512_8_3_3_2048_2048_0.2_0_Adam_base/training.log
  root: /home/luning/dev/projects/master-tf
  slack_api: 'https://hooks.slack.com/services/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'
train:
  batch_size: 50
  checkpoints:
    finetune: null
    interval: 2000
    monitor: +word_acc
    monitor_start: 0.9
    name: OCRTransformer
    resume: true
  epochs: 3000
  fp16: true
  loader_workers: 8
  log_interval: 100
  lr_scheduler:
    args:
      decay_rate: 0.1
      decay_steps: 70000
      initial_learning_rate: 0.0002
      staircase: false
    name: ExponentialDecay
  optim:
    args:
      lr: 0.0002
    name: Adam
version: 0.4.0
